Invoke-InstallStep "PuTTY Default Settings" {
	New-Item "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" -Force | Out-Null

	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "WarnOnClose" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "CloseOnExit" -Value 2 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Compression" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "AltF4" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FullScreenOnAltEnter" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "SunkenEdge" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "BlinkCur" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Beep" -Value 2 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "BeepInd" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "BellOverload" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "ScrollbackLines" -Value 0x270f -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "AutoWrapMode" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "TermWidth" -Value 0x82 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "TermHeight" -Value 0x23 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Font" -Value "Consolas" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FontCharSet" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FontHeight" -Value 0xa -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FontIsBold" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FontQuality" -Value 0x3 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "FontVTMode" -Value 0x4 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "BoldAsColour" -Value 0x2 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour0" -Value "203,204,205" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour1" -Value "203,204,205" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour2" -Value "7,54,66" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour3" -Value "7,54,66" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour4" -Value "203,204,205" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour5" -Value "173,173,39" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour6" -Value "0,0,0" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour7" -Value "203,204,205" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour8" -Value "194,54,33" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour9" -Value "194,54,33" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour10" -Value "37,188,36" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour11" -Value "37,188,36" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour12" -Value "173,173,39" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour13" -Value "173,173,39" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour14" -Value "73,46,225" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour15" -Value "73,46,225" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour16" -Value "249,53,248" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour17" -Value "249,53,248" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour18" -Value "20,240,240" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour19" -Value "20,240,240" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour20" -Value "233,235,235" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "Colour21" -Value "233,235,235" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "PasteRTF" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "LineCodePage" -Value "UTF-8" -Type String -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "ScrollOnKey" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "ScrollOnDisp" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "ScrollBar" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "ScrollBarFullScreen" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "LockSize" -Value 0 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "TCPKeepalives" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "SshProt" -Value 3 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "PingInterval" -Value 1 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "LinuxFunctionKeys" -Value 2 -Type DWord -Force | Out-Null
	New-ItemProperty "HKCU:\Software\SimonTatham\PuTTY\Sessions\Default%20Settings" "NoApplicationKeys" -Value 1 -Type DWord -Force | Out-Null
}